apps/accounts/urls.py
from django.urls import path

from .views import (
    UserRegisterView, 
    LoginView,
    LogoutView,
    UpdateUserView,
    PasswordResetView,
    CheckVerifyCodeView,
    PasswordResetConfirmView,
    Login_or_Logout_View,
)
app_name='accounts'
urlpatterns =[
    path('register/', UserRegisterView.as_view(), name='register' ),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('update/', UpdateUserView.as_view(), name='update'),
    path('password_reset/', PasswordResetView.as_view(), name = "password_reset"),
    path('check_verify_code/<uuid:uuid>/', CheckVerifyCodeView.as_view(), name="check_verify"),
    path('password_reset_confirm/<uuid:uuid>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('login_or_logout/', Login_or_Logout_View.as_view(), name=''),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.base.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('order/', include('apps.order.urls')),
    path('', include('apps.products.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from apps.base.models import BaseModel
from datetime import datetime, timedelta
import uuid
class User(AbstractUser):
    phone =models.CharField(max_length=20, null=True, blank=True)
    photos=models.ImageField(upload_to='users/', default='default/i.webp', blank=True)
    email=models.EmailField(unique=True)
    

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    def __str__(self):
        return self.username

EMAIL_EXPIRE_TIME = 5

class UserResetPasswordCode(BaseModel):
    private_id= models.UUIDField(default=uuid.uuid4, editable=False)
    email = models.EmailField(blank=True, unique=False, null=True)
    code=models.CharField(max_length=15, blank=True, null=True)
    expiration_time = models.DateTimeField(null=True, blank=True)
    is_confirmation = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.email} - {self.code}"
    def save(self, *args, **kwargs):
        self.expiration_time = datetime.now() + timedelta(minutes=EMAIL_EXPIRE_TIME)
        return super(UserResetPasswordCode, self).save(*args, **kwargs)
    





    

apps/accounts/forms.py
from django import forms
from django.forms.widgets import TextInput, PasswordInput, EmailInput
from .models import User, UserResetPasswordCode
from apps.base.utilits import VerifyEmailCode, CODE_LENGTH

class RegisterUserForm(forms.ModelForm):
    username = forms.CharField(widget=TextInput(attrs={'placeholder':'username...'}), required=True)
    email = forms.CharField(widget=TextInput(attrs={'placeholder':'email...'}), required=True)
    first_name = forms.CharField(widget=TextInput(attrs={'placeholder':'first_name...'}), required=True)
    last_name = forms.CharField(widget=TextInput(attrs={'placeholder':'last_name...'}), required=True)
    phone = forms.CharField(widget=TextInput(attrs={'placeholder':'phone...'}), required=True)
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'password...'}), required=True)
    confirm_password = forms.CharField(widget=TextInput(attrs={'placeholder':'confirm_password...'}), required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'phone')
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Bu email oldin ro'yxatdan o'tgan...")
        return email
    def clean_confirm_password(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('confirm_password')
        if password1 != password2:
            raise forms.ValidationError("Parollar bir-biriga mos emas...")
        return password2
    def save(self, commmit=True):
        password = self.cleaned_data.get('password')

        user = super().save(commmit)
        user.set_password(password)
        user.save()

        return user
    

class LoginForm(forms.Form):
    email = forms.EmailField(widget=EmailInput(attrs={'placeholder':'email'}), required=True)
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'password'}), required=True)
    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        if not email or not password:
            raise forms.ValidationError("Bo'sh bo'lmasligi kerak")
        return self.cleaned_data
    
    



class UpdateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email','first_name', 'last_name', 'photos')
    
class PasswordResetForm(forms.ModelForm):
    email=forms.EmailField(widget=TextInput(attrs={'placeholder':'Email Address'}), required=True)
    class Meta:
        model=UserResetPasswordCode
        fields=('email', )

    def clean(self):
        email = self.cleaned_data.get('email')
        is_email = User.objects.filter(email=email).exists()
        if not is_email:
            raise forms.ValidationError("Bunday emailga ega foydalanuvchi topilmadi...")
        
        return self.cleaned_data
    def save(self, commit=True):
        code_obj=VerifyEmailCode()

        
        code = code_obj.new_code()

        verify=super().save(commit)
        verify.code = code
        verify.save()

        return verify
    

class CheckVerifyCodeForm(forms.Form):
    code=forms.CharField(widget=PasswordInput(attrs={'placeholder':'code:'}),required=True)
    def clean(self):
        code=self.cleaned_data.get('code')

        if not code or not code.isnumeric() or len(code) != CODE_LENGTH:
            raise forms.ValidationError("Kod noto'g'ri formatda kiritildi...")
        
        return self.cleaned_data


class PasswordResetConfirmForm(forms.Form):
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'password...'}))
    confirm_password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'confirm password:'}))

    def clean_confirm_password(self):
        password1= self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('confirm_password')
        
        if password1!=password2:
            raise forms.ValidationError("Parollar bir-biriga mos emas!")
        return password2
    
    
    

apps/accounts/views.py
from datetime import datetime
from django.shortcuts import render, redirect
from django.views import View
from apps.accounts.forms import RegisterUserForm, LoginForm, UpdateUserForm, PasswordResetForm, CheckVerifyCodeForm, PasswordResetConfirmForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import User, UserResetPasswordCode
from apps.base.utilits import send_mail_code

class UserRegisterView(View):
    form_class = RegisterUserForm
    def get(self, request):
        form = self.form_class()
        context={
            "form":form
        }
        return render(request, 'accounts/register.html', context)
    def post(self, request):
        user_form = self.form_class(data=request.POST)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, "tizimdan muvaffaqiyatli ro'yxatdan o'tdingiz...")
            return redirect('home')

        messages.error(request, "Tizimdan ro'yxatdan o'ta olmadingiz...")
        context ={
            "form":"form",
        }
        return render(request, 'accounts/register.html', context)
    
class LoginView(View):
    form_class = LoginForm
    def get(self, request):
        form = self.form_class()
        context={
            'form':form
        }
        return render(request, "accounts/login.html", context)
    def post(self, request):
        user_form=self.form_class(data=request.POST)
        if user_form.is_valid():
            user=authenticate(request, username = user_form.cleaned_data['email'], password = user_form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, "siz tizimga muvaffaqiyatli kirdingiz...")
                return redirect("home")
            messages.error(request, "Login yoki parol noto'g'ri!!!")
            return render(request, "accounts/login.html", {'form': user_form})
        

        messages.error(request, user_form.errors)
        return render(request, "accounts/login.html", {'form': user_form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('home')
    

class UpdateUserView(View):
    form_class = UpdateUserForm
    def get(self, request):
        form = self.form_class(instance=request.user)
        context={
            'form':form
        }
        return render(request, "accounts/update_profile.html", context )
    def post(self, request):
        user_form=self.form_class(data=request.POST, files=request.FILES, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            messages.success(request, "Muvaffaqiyatli yangilandi...")
            return redirect("home")
        messages.error(request, user_form.errors)
        return render(request, 'accounts/update_profile.html', {'form':user_form})

    
class PasswordResetView(View):
    form_class = PasswordResetForm
    def get(self, request):
        form = self.form_class()
        context={
            'form':form
        }
        return render(request, "accounts/password_reset_form.html", context)

    def post(self, request, *args, **kwargs):
        email_form = self.form_class(request.POST)
        if email_form.is_valid():
            verify = email_form.save()
            print(verify)
            
            send_mail_code(verify.email, verify.code)
            messages.success(request, "Emailingizga kod yuborildi...")
            return redirect("accounts:check_verify", uuid=verify.id)
        
         
        messages.error(request, 'qandaydir xatolik yuz berdi')
        return render(request, 'accounts/password_reset_form.html', {'email_form':email_form})
    
class CheckVerifyCodeView(View):
    form_class =CheckVerifyCodeForm

    def get(self, request, uuid):
        form = self.form_class()
        context={
            'form':form
        }
        return render(request, "accounts/password_reset_check_verify_code.html", context)
    def post(self, request, uuid):
        verify_form = self.form_class(request.POST)
        if not verify_form.is_valid():
            messages.error(request, verify_form.errors)
            return render(request, "accounts/password_reset_check_verify_code.html", {'form':verify_form})
        
        code = verify_form.cleaned_data.get('code')

        verify_code=UserResetPasswordCode.objects.filter(id=uuid, expiration_time__gte=datetime.now(), is_confirmation=False, code=code).first()
        if not verify_code:
            messages.error(request, "Kod xato yoki vaqti tugagan iltimos qayta urinib ko'ring...")
            return render(request, "accounts/password_reset_check_verify_code.html", {'form':verify_form})
        
        verify_code.is_confirmation = True
        verify_code.save()

        messages.success(request, "kod to'g'ri endi yangi parol kiriting:")
        return redirect("accounts:password_reset_confirm", uuid=uuid)
    
class PasswordResetConfirmView(View):
    form_class= PasswordResetConfirmForm

    def get(self, request, uuid):
        form =self.form_class()
        context={
            'form':form
        }
        return render(request, 'accounts/password_reset_confirm.html', context)

    def post(self, request, uuid):
        password_form = self.form_class(request.POST)
        if password_form.is_valid():
            email = UserResetPasswordCode.objects.get(id=uuid).email
            user = User.objects.get(email=email)
            password = password_form.cleaned_data.get('password')
            user.set_password(password)
            user.save()
            messages.success(request, "Parollaringiz o'zgartirildi...")
            return redirect("accounts:login")
        messages.error(request, password_form.errors)
        return render(request, "accounts/password_reset_confirm.html", {"form": password_form})
    
        

class Login_or_Logout_View(View):
    def get(self, request):
        return render(request, 'home.html')     



            

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Login
{% endblock title %}
{% block content %}
    <div class="container">

    <form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Login' style="color:blue; background-color: aqua;">
    
    </form >
<br>
    <p><a href="{% url 'accounts:password_reset' %}"> <button type="button" class="btn btn-link">Reset Password</button>  </a></p>
    <br>
</div>

{% endblock content %}

templates/accounts/password_reset_check_verify_code.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Check Verify Code
{% endblock title %}
{% block content %}
    <form method='POST'>
    {% csrf_token %}
    <h2>Emailingizga yuborilgan 6 xonali kodni kiriting kodning amal qilish muddati 5 minut...</h2>

    {{ form.as_p }}
    <input type='submit' value='Check code' style="background-color: aqua; color: blue;">
    <a href="{% url 'accounts:password_reset' %}"> <button type="button" class="btn btn-info">Back</button> </a>
    
    </form >
{% endblock content %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}
Enter new Password 
{% endblock %}
{% block content %}
<h1>Set a new password!</h1>
<form method="POST">
{% csrf_token %}
{{ form.as_p }}

<input type="submit" value = "Change my password" style="background-color: aqua; color: blue;">
</form>
{% endblock %}

templates/accounts/password_reset_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password Reset</title>

</head>
<body>
    <p>Salom,</p>
    <p>Sizning parolingizni tiklash uchun kodingiz: <strong>{{ code }}</strong></p>
    <p>Agar siz parolingizni qayta tiklashni talab qilmagan bo'lsangiz, shunchaki bu xabarni bee'tibor qoldiring...</p>
    <p>Yana savollaringiz bo'lsa biz bilan bog'lanishingiz mumkin.</p>
    <p>Phone: +998972001426 </p>

</body>
</html>

templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% block title %}
Forgot your password?
{% endblock title %}

{% block content %}

    <h1>Forgot your password?</h1>
    <p>Emailingizni kiriting:</p>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="kodni yuborish" style="color: blue; background-color: aqua;">
    </form>

{% endblock content %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Register
{% endblock title %}
{% block content %}
    <form method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Register'>
    <a href="{% url 'home' %}">  <button type="button" class="btn btn-info">Back</button> </a>
    
    </form >

{% endblock content %}

templates/accounts/update_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Update your profile
{% endblock title %}
{% block content %}
    <div class="container">
        <form method='POST' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Update' class="btn btn-info" style="background-color: aqua; color: blue;">

        </form >
        
        <br>
        <p><a href="{% url 'home' %}"> <button type="button" class="btn btn-warning">Back</button>  </a></p>
        <br>
    </div>

{% endblock content %}