apps/accounts/urls.py
from django.urls import path

from .views import (
    UserRegisterView, 
    LoginView,
    LogoutView,
    UpdateUserView,
    PasswordResetView,
    CheckVerifyCodeView,
    PasswordResetConfirmView,
    Login_or_Logout_View,
)
app_name='accounts'
urlpatterns =[
    path('register/', UserRegisterView.as_view(), name='register' ),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('update/', UpdateUserView.as_view(), name='update'),
    path('password_reset/', PasswordResetView.as_view(), name = "password_reset"),
    path('check_verify_code/<uuid:uuid>/', CheckVerifyCodeView.as_view(), name="check_verify"),
    path('password_reset_confirm/<uuid:uuid>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('login_or_logout/', Login_or_Logout_View.as_view(), name=''),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.base.views import index
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.accounts.urls')),
    path('order/', include('apps.order.urls')),
    path('', include('apps.products.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/base/models.py
from django.db import models
from uuid import uuid4

class BaseModel(models.Model):
    id =models.UUIDField(primary_key=True, default=uuid4, editable=False )
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    is_active=models.BooleanField(default=True)

    class Meta:
        abstract=True

apps/base/views.py
from django.shortcuts import render
from .utilits import send_mail_code
# Create your views here.

def index(request):
    # send_mail_code('toshniyozovogabek0627@gmail.com', 111222)
    return render(request, "home.html", {})

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Index page
{% endblock title %}
{% block content %}
    home page
    <p>
    {% if user.is_authenticated %}
        <div class="container">
            Welcome, {{ user.username }}
            <p><a href="{% url 'accounts:update' %}"> <button type="button" class="btn btn-primary">Update</button></a></p>
            <p><a href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-warning">Logout</button></a></p>
        </div>    
    {% else %}
        <div class="container">

            Welcome, guest! 
            <br>
            <p><a href="{% url 'accounts:login' %}"><button type="button" class="btn btn-primary">Login</button></a></p>
            <p><a href="{% url 'accounts:register' %}"><button type="button" class="btn btn-info">Register</button></a></p>
        </div>    
        
    {% endif %}
    </p>
{% endblock content %}